### ISSUE TITLE
请问要如何才能启动NeXT-Server

### ISSUE THREAD

**Issue by wans10** [SSPanel-NeXT/NeXT-Server#38]
大佬您好，我按照 https://nextpanel.dev/docs/advanced/next-repo 文档安装了NeXT-Server，对应NeX-Panel版本为24.4.0，节点Vmess+ws，但是NeXT-Server无法启动，请问应该如何启动？谢谢。
NeXT-Server配置如下：
Log:
  Level: warning # Log level: none, error, warning, info, debug 
  AccessPath: # /etc/next-server/access.Log
  ErrorPath: # /etc/next-server/error.log
DnsConfigPath: # /etc/next-server/dns.json
RouteConfigPath: # /etc/next-server/route.json
InboundConfigPath: # /etc/next-server/custom_inbound.json
OutboundConfigPath: # /etc/next-server/custom_outbound.json
ConnectionConfig:
  Handshake: 4 # Handshake time limit, Second
  ConnIdle: 30 # Connection idle time limit, Second
  UplinkOnly: 2 # Time limit when the connection downstream is closed, Second
  DownlinkOnly: 4 # Time limit when the connection is closed after the uplink is closed, Second
  BufferSize: 64 # The internal cache size of each connection, kB
Nodes:
  - PanelType: "nextpanel-v1(wip)" # Panel type: sspanel-old, nextpanel-v1(wip)
    ApiConfig:
      ApiHost: "https://domain.com"
      ApiKey: "123456"
      NodeID: 1
      NodeType: vmess # Node type: vmess, trojan, shadowsocks, shadowsocks2022
      Timeout: 30 # Timeout for the api request
      SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
      DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
      RuleListPath: # /etc/next-server/rulelist Path to local rulelist file
    ControllerConfig:
      ListenIP: 0.0.0.0 # IP address you want to listen
      SendIP: 0.0.0.0 # IP address you want to send pacakage
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
      CertConfig:
        CertMode: dns # Option about how to get certificate: none, file, http, tls, dns. Choose "none" will forcedly disable the tls config.
        CertDomain: "hkg1.domain.com" # Domain to cert
        CertFile: /etc/next-server/cert/hkg1.domain.com.cert # Provided if the CertMode is file
        KeyFile: /etc/next-server/cert/hkg1.domain.com.key
        Provider:  cloudflare # cloudflare # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        Email: xxx@xxx.com
        DNSEnv: # DNS ENV option used by DNS provider
           CLOUDFLARE_EMAIL: you@example.com
           CLOUDFLARE_API_KEY: 123456
          # CF_DNS_API_TOKEN: xxx
      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
      DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
      DisableUploadTraffic: false # Disable upload traffic to API
      DisableGetRule: false # Disable get rule
      EnableProxyProtocol: false # Only works for WebSocket and TCP
      DisableIVCheck: false # Disable IV check
      DisableSniffing: false # Disable sniffing
      AutoSpeedLimitConfig:
        Limit: 0 # Warned speed. Set to 0 to disable AutoSpeedLimit (mbps)
        WarnTimes: 0 # After (WarnTimes) consecutive warnings, the user will be limited. Set to 0 to punish overspeed user immediately.
        LimitSpeed: 0 # The speedlimit of a limited user (unit: mbps)
        LimitDuration: 0 # How many minutes will the limiting last (unit: minute)

**Comment by AutisticShark** [comment]
https://www.redhat.com/sysadmin/linux-systemctl-manage-services

And 

PanelType should be `sspanel-old` since the new node API is not ready yet

**Comment by wans10** [comment]
@AutisticShark THX
